import { spawn, execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { projectRoot, isGitCheckout, dataDir } from '../../../lib/paths';
import { homedir, tmpdir } from 'node:os';
import path from 'node:path';
import { repoSlug, compareVersions, installKind, updateCommand } from '../../../lib/release';
import {
  bundleRefusal, dataRefusal, lastUpdateReport, planFromRelease, releaseSource, runningBundle,
} from '../../../lib/updater';
import {
  bundleFacts, cancelUpdate, currentUpdate, macFacts, readStatusFile, startUpdate, updatePaths,
} from '../../../lib/updater-job';
import { scanIsRunning } from '../../../lib/scan-state';
import pkg from '../../../package.json';

// Updating, when the app is a git checkout.
//
// The spec forbids an update *check* — meaning a silent one that runs on its
// own and phones home every launch. This is the opposite of that: nothing
// happens until someone presses a button, nothing about the user is sent, and
// the whole thing is `git fetch` and `git pull` against the remote the checkout
// already has. It exists because "run git pull first" is a step people forget,
// and then they hit bugs that were fixed weeks ago.
//
// The Mac app can also install a release itself, on a second click
// (installedPost below, lib/updater-job.js).
//
// Gated with the destructive routes: it changes the code that will run next.

const GIT_TIMEOUT = 60000;

// What the server was serving when it started.
//
// `git pull` changes the files on disk. It does not change the code already
// loaded into a running server, and nothing used to say so — you update, the
// app looks identical, and the reasonable conclusion is that the update failed.
// Recording HEAD at startup lets the app notice that the disk has moved on and
// say "restart me" instead of leaving you to work it out.
let bootSha = null;
function shaAtBoot(root) {
  if (bootSha === null) {
    try {
      bootSha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: root })
        .toString().trim();
    } catch {
      bootSha = '';
    }
  }
  return bootSha;
}

function git(args, cwd) {
  return new Promise((resolve) => {
    let out = '';
    let err = '';
    let child;
    try {
      child = spawn('git', args, { cwd });
    } catch (e) {
      return resolve({ code: -1, out: '', err: e.message });
    }
    const timer = setTimeout(() => { try { child.kill(); } catch {} }, GIT_TIMEOUT);
    child.stdout.on('data', (d) => { out += d.toString(); });
    child.stderr.on('data', (d) => { err += d.toString(); });
    child.on('error', (e) => { clearTimeout(timer); resolve({ code: -1, out, err: e.message }); });
    // `raw` matters: porcelain status lines begin with a significant space, and
    // trimming the block eats it off the first line only — which silently
    // corrupts exactly one filename and nothing else.
    child.on('close', (code) => {
      clearTimeout(timer);
      resolve({ code, out: out.trim(), raw: out, err: err.trim() });
    });
  });
}

async function localState(root) {
  const [sha, subject, status, branch] = await Promise.all([
    git(['rev-parse', '--short', 'HEAD'], root),
    git(['log', '-1', '--pretty=%s'], root),
    git(['status', '--porcelain'], root),
    git(['rev-parse', '--abbrev-ref', 'HEAD'], root),
  ]);

  // package-lock.json is regenerated by npm and differs between npm versions,
  // so it reads as modified on a machine that merely ran `npm install`. It is
  // treated separately because it is safe to discard and everything else is not.
  const dirty = (status.raw || '')
    .split('\n')
    .filter((l) => l.length > 3)
    .map((l) => l.slice(3).trim())
    .filter(Boolean);
  const onlyLockfile = dirty.length > 0 && dirty.every((f) => f === 'package-lock.json');

  return { sha: sha.out, subject: subject.out, branch: branch.out, dirty, onlyLockfile };
}

// An installed copy — the Mac app or the npm package — has no checkout to pull.
// Its button asks GitHub for the newest release's version number instead and
// compares it with the one baked into this build. One GET to GitHub, only when
// the button is pressed, carrying nothing about the user: the spec's invariant 2
// names exactly this as permitted. Never call it from anything that runs on its own.
// In the Mac app a second, separate press ("Install and restart") may then
// download that release's disk image and SHA256SUMS and install it (invariant 2
// again). Nothing is downloaded before that press.

// The folder this copy keeps its network in, when it isn't the default one.
function customDataDir() {
  const dir = dataDir();
  return path.resolve(dir) === path.join(homedir(), '.six-degrees') ? null : dir;
}

function installedInfo(root) {
  const slug = repoSlug(pkg.repository);
  const kind = installKind(process.env, root || '');
  const info = {
    supported: false,
    installed: true,
    kind,
    version: pkg.version,
    slug,
    command: slug ? updateCommand(kind, slug, { dataDir: customDataDir() }) : null,
  };
  if (kind === 'mac-app') {
    // How the last in-app update went (written by scripts/apply-update.sh),
    // and one in progress, so the page can pick it up again. Local files and
    // memory only: this GET runs on every page (StaleServerBanner).
    info.lastUpdate = lastUpdateReport(readStatusFile(updatePaths().statusFile), { runningVersion: pkg.version });
    info.job = currentUpdate();
  }
  // A test's release server in place of GitHub is said out loud, never silent.
  const source = releaseSource(process.env);
  if (source.test) info.testReleases = source.apiBase;
  return info;
}

async function latestRelease(slug, apiBase) {
  const res = await fetch(`${apiBase}/repos/${slug}/releases/latest`, {
    headers: { Accept: 'application/vnd.github+json', 'User-Agent': 'six-degrees-update-check' },
    signal: AbortSignal.timeout(10000),
    cache: 'no-store',
  });
  if (res.status === 404) return null;           // nothing published yet
  if (!res.ok) throw new Error(`GitHub answered ${res.status}`);
  const d = await res.json();
  return {
    version: String(d.tag_name || '').replace(/^v/i, ''),
    url: d.html_url || null,
    release: d,                                  // for the Mac app's install check; not sent to the page
  };
}

// The Mac app's update helper, shipped inside the app (scripts/build-app.mjs).
function helperPath(root) {
  const file = root ? path.join(root, 'scripts', 'apply-update.sh') : null;
  return file && existsSync(file) ? file : null;
}

// Can the Mac app replace itself where it is? Every fact is read here, on the
// server; the page sends only which action it wants.
function macInstall(root) {
  if (process.platform !== 'darwin') {
    return { refusal: { code: 'not-mac', message: 'Installing an update from here works only in the Mac app.' } };
  }
  const bundle = runningBundle({ app: process.env.SIX_DEGREES_APP, root });
  const refusal = bundleRefusal(bundle, bundleFacts(bundle))
    || dataRefusal({ dataDir: dataDir(), bundle })
    || (helperPath(root) ? null : { code: 'no-helper', message: "This copy doesn't include the update helper, so it can't replace itself." });
  return { bundle, refusal };
}

// Updating an installed copy: the Mac app or the npm package.
//
//   check-release   one GET to GitHub for the newest release (the spec's
//                   permitted click). For the Mac app it also says whether that
//                   release can be installed from here, and if not, why not.
//   install-release the second click, Mac app only: download, check and stage
//                   it in the background (lib/updater-job.js), then restart
//   update-status   how that is going (local, no network)
//   cancel-install  stop it, until it restarts
async function installedPost(action, root) {
  const info = installedInfo(root);
  // GitHub, or a test's server on 127.0.0.1 (lib/updater.js releaseSource).
  const source = releaseSource(process.env);

  if (action === 'update-status') return Response.json({ job: currentUpdate() });
  if (action === 'cancel-install') return Response.json({ job: cancelUpdate() });

  if (action === 'check-release') {
    if (!info.slug) {
      return Response.json({ error: 'This copy does not say where it was published.' }, { status: 400 });
    }
    try {
      const latest = await latestRelease(info.slug, source.apiBase);
      const newer = Boolean(latest && compareVersions(latest.version, info.version) > 0);
      let install = null;
      if (newer && info.kind === 'mac-app') {
        const { refusal } = macInstall(root);
        const planned = refusal ? null : planFromRelease(latest.release, {
          currentVersion: info.version, chip: macFacts().chip, slug: info.slug, downloadBase: source.downloadBase,
        });
        const reason = refusal?.message || planned?.refusal?.message || null;
        install = reason ? { possible: false, reason } : { possible: true, size: planned.plan.dmg.size };
      }
      return Response.json({
        ...info,
        latest: latest && { version: latest.version, url: latest.url },
        newer,
        install,
      });
    } catch (e) {
      return Response.json({ error: `Could not reach GitHub (${e.message}). Try again in a moment.` }, { status: 502 });
    }
  }

  if (action === 'install-release') {
    if (info.kind !== 'mac-app') {
      return Response.json(
        { error: 'Only the Mac app can install an update itself. Use the line below instead.', command: info.command },
        { status: 400 },
      );
    }
    if (!info.slug) {
      return Response.json({ error: 'This copy does not say where it was published.' }, { status: 400 });
    }
    const { bundle, refusal } = macInstall(root);
    if (refusal) {
      return Response.json({ error: refusal.message, refusal: refusal.code, command: info.command }, { status: 409 });
    }
    // Quitting mid-scan would stop it half-way; the job looks again just before it restarts.
    if (scanIsRunning()) {
      return Response.json(
        { error: 'A scan is running. Let it finish or stop it, then install the update.', command: info.command },
        { status: 409 },
      );
    }
    const mac = macFacts();
    const started = startUpdate({
      slug: info.slug,
      currentVersion: info.version,
      chip: mac.chip,
      macosVersion: mac.macosVersion,
      bundle,
      dataDir: dataDir(),
      defaultDataDir: path.join(homedir(), '.six-degrees'),
      helper: helperPath(root),
      tmpRoot: tmpdir(),
      ...updatePaths(),
      apiBase: source.apiBase,
      downloadBase: source.downloadBase,
      scanRunning: scanIsRunning,
    });
    if (started.error) return Response.json({ error: started.error, job: started.job }, { status: 409 });
    return Response.json({ job: started.job }, { status: 202 });
  }

  return Response.json({ error: 'Not a git checkout.' }, { status: 400 });
}

export async function GET() {
  const root = projectRoot();
  if (!isGitCheckout()) {
    // Local facts only — the network is touched by POST, on a click.
    return Response.json(installedInfo(root));
  }
  const state = await localState(root);
  const boot = shaAtBoot(root);
  return Response.json({
    supported: true,
    ...state,
    bootSha: boot,
    // The files moved after this process started, so what you are looking at is
    // not what is on disk.
    restartNeeded: Boolean(boot && state.sha && boot !== state.sha),
  });
}

export async function POST(request) {
  const root = projectRoot();

  let body = {};
  try { body = await request.json(); } catch {}
  const action = String(body.action || '');

  if (!isGitCheckout()) return installedPost(action, root);

  if (action === 'check') {
    const fetched = await git(['fetch', '--quiet', 'origin'], root);
    if (fetched.code !== 0) {
      return Response.json(
        { error: `Could not reach GitHub: ${fetched.err.slice(0, 200)}` },
        { status: 502 }
      );
    }
    const state = await localState(root);
    const upstream = `origin/${state.branch || 'main'}`;
    const [behind, log] = await Promise.all([
      git(['rev-list', '--count', `HEAD..${upstream}`], root),
      git(['log', '--pretty=%h %s', `HEAD..${upstream}`], root),
    ]);
    const count = Number(behind.out || 0);
    return Response.json({
      ...state,
      behind: Number.isFinite(count) ? count : 0,
      commits: (log.out || '').split('\n').filter(Boolean).slice(0, 25),
    });
  }

  if (action === 'pull') {
    const state = await localState(root);

    // Discarding a generated lockfile is safe. Discarding anything else is the
    // user's call, not ours.
    if (state.dirty.length && !state.onlyLockfile) {
      return Response.json(
        { error: 'There are local changes here, so nothing was updated.', dirty: state.dirty },
        { status: 409 }
      );
    }
    if (state.onlyLockfile) {
      await git(['checkout', '--', 'package-lock.json'], root);
    }

    const pulled = await git(['pull', '--ff-only'], root);
    if (pulled.code !== 0) {
      return Response.json(
        { error: pulled.err.slice(0, 400) || 'The update could not be applied automatically.' },
        { status: 409 }
      );
    }

    const after = await localState(root);
    // A changed package.json means new scripts or dependencies, and this server
    // started before they existed.
    const needsRestart = /package(-lock)?\.json/.test(pulled.out);
    return Response.json({
      ok: true,
      output: pulled.out.split('\n').slice(-40).join('\n'),
      sha: after.sha,
      subject: after.subject,
      needsRestart,
    });
  }

  return Response.json({ error: `Unknown action '${action}'` }, { status: 400 });
}
