import { spawn, execFileSync } from 'node:child_process';
import { projectRoot, isGitCheckout } from '../../../lib/paths';

// Updating, when the app is a git checkout.
//
// The spec forbids an update *check* — meaning a silent one that runs on its
// own and phones home every launch. This is the opposite of that: nothing
// happens until someone presses a button, nothing about the user is sent, and
// the whole thing is `git fetch` and `git pull` against the remote the checkout
// already has. It exists because "run git pull first" is a step people forget,
// and then they hit bugs that were fixed weeks ago.
//
// Gated with the destructive routes: it changes the code that will run next.

const GIT_TIMEOUT = 60000;

// What the server was serving when it started.
//
// `git pull` changes the files on disk. It does not change the code already
// loaded into a running server, and nothing used to say so — you update, the
// app looks identical, and the reasonable conclusion is that the update failed.
// Recording HEAD at startup lets the app notice that the disk has moved on and
// say "restart me" instead of leaving you to work it out.
let bootSha = null;
function shaAtBoot(root) {
  if (bootSha === null) {
    try {
      bootSha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: root })
        .toString().trim();
    } catch {
      bootSha = '';
    }
  }
  return bootSha;
}

function git(args, cwd) {
  return new Promise((resolve) => {
    let out = '';
    let err = '';
    let child;
    try {
      child = spawn('git', args, { cwd });
    } catch (e) {
      return resolve({ code: -1, out: '', err: e.message });
    }
    const timer = setTimeout(() => { try { child.kill(); } catch {} }, GIT_TIMEOUT);
    child.stdout.on('data', (d) => { out += d.toString(); });
    child.stderr.on('data', (d) => { err += d.toString(); });
    child.on('error', (e) => { clearTimeout(timer); resolve({ code: -1, out, err: e.message }); });
    // `raw` matters: porcelain status lines begin with a significant space, and
    // trimming the block eats it off the first line only — which silently
    // corrupts exactly one filename and nothing else.
    child.on('close', (code) => {
      clearTimeout(timer);
      resolve({ code, out: out.trim(), raw: out, err: err.trim() });
    });
  });
}

async function localState(root) {
  const [sha, subject, status, branch] = await Promise.all([
    git(['rev-parse', '--short', 'HEAD'], root),
    git(['log', '-1', '--pretty=%s'], root),
    git(['status', '--porcelain'], root),
    git(['rev-parse', '--abbrev-ref', 'HEAD'], root),
  ]);

  // package-lock.json is regenerated by npm and differs between npm versions,
  // so it reads as modified on a machine that merely ran `npm install`. It is
  // treated separately because it is safe to discard and everything else is not.
  const dirty = (status.raw || '')
    .split('\n')
    .filter((l) => l.length > 3)
    .map((l) => l.slice(3).trim())
    .filter(Boolean);
  const onlyLockfile = dirty.length > 0 && dirty.every((f) => f === 'package-lock.json');

  return { sha: sha.out, subject: subject.out, branch: branch.out, dirty, onlyLockfile };
}

export async function GET() {
  const root = projectRoot();
  if (!isGitCheckout()) {
    return Response.json({
      supported: false,
      reason: 'This copy was installed rather than cloned, so there is nothing to pull. Run npx six-degrees@latest for the current version.',
    });
  }
  const state = await localState(root);
  const boot = shaAtBoot(root);
  return Response.json({
    supported: true,
    ...state,
    bootSha: boot,
    // The files moved after this process started, so what you are looking at is
    // not what is on disk.
    restartNeeded: Boolean(boot && state.sha && boot !== state.sha),
  });
}

export async function POST(request) {
  const root = projectRoot();
  if (!isGitCheckout()) {
    return Response.json({ error: 'Not a git checkout.' }, { status: 400 });
  }

  let body = {};
  try { body = await request.json(); } catch {}
  const action = String(body.action || '');

  if (action === 'check') {
    const fetched = await git(['fetch', '--quiet', 'origin'], root);
    if (fetched.code !== 0) {
      return Response.json(
        { error: `Could not reach GitHub: ${fetched.err.slice(0, 200)}` },
        { status: 502 }
      );
    }
    const state = await localState(root);
    const upstream = `origin/${state.branch || 'main'}`;
    const [behind, log] = await Promise.all([
      git(['rev-list', '--count', `HEAD..${upstream}`], root),
      git(['log', '--pretty=%h %s', `HEAD..${upstream}`], root),
    ]);
    const count = Number(behind.out || 0);
    return Response.json({
      ...state,
      behind: Number.isFinite(count) ? count : 0,
      commits: (log.out || '').split('\n').filter(Boolean).slice(0, 25),
    });
  }

  if (action === 'pull') {
    const state = await localState(root);

    // Discarding a generated lockfile is safe. Discarding anything else is the
    // user's call, not ours.
    if (state.dirty.length && !state.onlyLockfile) {
      return Response.json(
        { error: 'There are local changes here, so nothing was updated.', dirty: state.dirty },
        { status: 409 }
      );
    }
    if (state.onlyLockfile) {
      await git(['checkout', '--', 'package-lock.json'], root);
    }

    const pulled = await git(['pull', '--ff-only'], root);
    if (pulled.code !== 0) {
      return Response.json(
        { error: pulled.err.slice(0, 400) || 'The update could not be applied automatically.' },
        { status: 409 }
      );
    }

    const after = await localState(root);
    // A changed package.json means new scripts or dependencies, and this server
    // started before they existed.
    const needsRestart = /package(-lock)?\.json/.test(pulled.out);
    return Response.json({
      ok: true,
      output: pulled.out.split('\n').slice(-40).join('\n'),
      sha: after.sha,
      subject: after.subject,
      needsRestart,
    });
  }

  return Response.json({ error: `Unknown action '${action}'` }, { status: 400 });
}
